version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: ../.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: ../.env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghwa/data/mariadb


  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghwa/data/wordpress

networks:
  inception:
    driver: bridge
